import { Platform, StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  mainContainer: { flex: 1 },
  roleIcon: {
    position: "absolute",
    bottom: -2,
    right: -2,
    backgroundColor: "#0f172a",
    borderRadius: 999,
    width: 14,
    height: 14,
    alignItems: "center",
    justifyContent: "center",
  },

  // Header
  header: {
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.05)",
  },
  backBtn: { width: 40 },
  headerCenter: { flex: 1, alignItems: "center" },
  headerTitle: { color: "white", fontSize: 16, fontWeight: "700" },
  headerSubtitle: { color: "#94a3b8", fontSize: 12, marginTop: 2 },
  headerActions: { flexDirection: "row", alignItems: "center", gap: 4 },
  actionBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  strangerBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 2,
    backgroundColor: "rgba(148,163,184,0.1)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.2)",
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  strangerBadgeText: { color: "#94a3b8", fontSize: 10, marginLeft: 3 },

  // Pinned banner
  pinnedBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    margin: 10,
    marginBottom: 0,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(96,165,250,.35)",
    backgroundColor: "rgba(37,99,235,.12)",
    padding: 8,
  },
  pinnedBannerText: { flex: 1, color: "#dbeafe", fontSize: 12 },
  pinnedBannerCount: { color: "#bfdbfe", fontSize: 11, fontWeight: "600" },

  // System message
  systemMsgWrapper: { alignItems: "center", marginVertical: 8 },
  systemMsgText: {
    fontSize: 12,
    color: "#94a3b8",
    backgroundColor: "rgba(148,163,184,0.1)",
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 4,
    overflow: "hidden",
  },

  // Messages
  listContent: { padding: 16, paddingBottom: 8 },
  msgWrapper: { marginBottom: 10 },
  senderName: {
    fontSize: 11,
    color: "#94a3b8",
    marginBottom: 2,
    marginLeft: 36,
  },
  msgRow: { flexDirection: "row", alignItems: "center", gap: 4 },
  msgRowMine: { justifyContent: "flex-end" },
  msgRowOther: { justifyContent: "flex-start" },
  msgRowPoll: { justifyContent: "center" },

  reactionBtn: {
    width: 26,
    height: 26,
    alignItems: "center",
    justifyContent: "center",
  },

  // Bubble
  bubble: {
    maxWidth: "72%",
    padding: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.18)",
  },
  pollCardShell: {
    width: "100%",
    maxWidth: 420,
    padding: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
  },
  imageCardShell: {
    maxWidth: 220,
    padding: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    borderRadius: 0,
  },
  attachmentCardShell: {
    maxWidth: "78%",
    padding: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    borderRadius: 0,
  },
  myBubble: { backgroundColor: "#1d4ed8", borderBottomRightRadius: 4 },
  otherBubble: { backgroundColor: "#1e293b", borderBottomLeftRadius: 4 },
  recalledBubble: {
    backgroundColor: "rgba(15,23,42,0.4)",
    borderStyle: "dashed",
    borderColor: "rgba(148,163,184,0.45)",
  },
  msgText: { color: "#e2e8f0", fontSize: 15, lineHeight: 21 },
  msgTextMine: { color: "white" },

  // Reactions
  reactionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 4,
    gap: 4,
  },
  reactionChip: {
    borderWidth: 1,
    borderColor: "rgba(148,163,184,.3)",
    backgroundColor: "rgba(15,23,42,.75)",
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  reactionChipText: { color: "#e2e8f0", fontSize: 12 },

  msgTimeRow: { marginTop: 4 },
  msgTimeRowMine: { alignItems: "flex-end", paddingRight: 6 },
  msgTimeRowOther: { alignItems: "flex-start", paddingLeft: 6 },
  msgTimeRowCenter: { alignItems: "center" },
  msgTime: { fontSize: 10, fontWeight: "500" },
  msgTimeMine: { color: "#cbd5e1" },
  msgTimeOther: { color: "#94a3b8" },
  msgTimeLightCard: { color: "#64748b" },
  editedLabel: { fontSize: 10, fontStyle: "italic", color: "#cbd5e1" },
  recalledText: { color: "#94a3b8", fontStyle: "italic", fontSize: 13 },

  // Seen
  seenRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    paddingRight: 6,
    marginTop: 2,
  },
  seenAvatar: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#60a5fa",
  },
  seenAvatarPlaceholder: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "#1e293b",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "#60a5fa",
  },

  // Reply quote inside bubble
  replyQuote: {
    borderLeftWidth: 3,
    borderLeftColor: "rgba(59,130,246,0.9)",
    backgroundColor: "rgba(2,132,199,0.12)",
    borderRadius: 8,
    padding: 7,
    marginBottom: 6,
  },
  replyQuoteName: { color: "#bfdbfe", fontWeight: "600", fontSize: 12 },
  replyQuotePreview: { color: "#cbd5e1", fontSize: 12, marginTop: 2 },

  // Emoji message
  emojiMsg: { fontSize: 32, lineHeight: 40 },

  // Image message
  imageMsg: { width: 200, height: 200, borderRadius: 12 },

  // File
  fileMsg: { color: "#1e40af", fontSize: 14, fontWeight: "600" },
  fileAction: {
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.38)",
    backgroundColor: "#f8fafc",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 4,
  },
  fileHint: { color: "#64748b", fontSize: 11 },

  // Audio
  audioMsg: { color: "#0f172a", fontSize: 14, fontWeight: "600" },
  audioPlayer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.38)",
    backgroundColor: "#f8fafc",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  audioPlayBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.38)",
    backgroundColor: "rgba(15,23,42,0.06)",
    alignItems: "center",
    justifyContent: "center",
  },

  // Sticker
  stickerMsg: { width: 120, height: 120 },

  // Call card
  callCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(96,165,250,.2)",
    backgroundColor: "rgba(15,23,42,.96)",
    minWidth: 200,
  },
  callIconWrapper: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  callLabel: { color: "#f8fafc", fontWeight: "700", fontSize: 13 },
  callDuration: { color: "#cbd5e1", fontSize: 11, marginTop: 2 },
  callUpgradeNote: { color: "#93c5fd", fontSize: 11, marginTop: 2 },

  // Poll
  pollContainer: {
    minWidth: 240,
    backgroundColor: "#18181b",
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    gap: 10,
  },
  pollQuestion: {
    color: "#fafafa",
    fontWeight: "700",
    fontSize: 15,
    marginBottom: 2,
  },
  pollMeta: { color: "#71717a", fontSize: 12, marginBottom: 6 },
  pollOption: {
    position: "relative",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#27272a",
    borderRadius: 10,
    padding: 10,
    marginBottom: 6,
    backgroundColor: "#09090b",
  },
  pollOptionVoted: {
    borderColor: "#6366f1",
    backgroundColor: "rgba(99,102,241,0.05)",
  },
  pollBar: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: "rgba(255,255,255,0.03)",
    zIndex: 0,
  },
  pollOptionContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    zIndex: 1,
  },
  pollOptionLabel: { color: "#e4e4e7", fontWeight: "600", fontSize: 13 },
  pollOptionLabelVoted: { color: "#818cf8" },
  pollPercent: { color: "#71717a", fontWeight: "700", fontSize: 12 },
  pollPercentVoted: { color: "#818cf8" },
  pollDetailBtn: {
    marginTop: 4,
    borderWidth: 1,
    borderColor: "rgba(96,165,250,0.35)",
    backgroundColor: "rgba(37,99,235,0.12)",
    borderRadius: 10,
    paddingVertical: 9,
    alignItems: "center",
  },
  pollDetailBtnText: { color: "#bfdbfe", fontSize: 13, fontWeight: "700" },

  voteModalOverlay: {
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 14,
  },
  voteModalSheet: { width: "92%", borderRadius: 18, paddingBottom: 10 },
  voteModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  voteCloseBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.25)",
    backgroundColor: "rgba(15,23,42,0.3)",
  },
  voteModalQuestion: { color: "#cbd5e1", fontSize: 13, marginBottom: 12 },
  voteTabsRow: { gap: 8, paddingBottom: 10 },
  voteTab: {
    width: 200,
    height: 50,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.25)",
    backgroundColor: "rgba(255,255,255,0.04)",
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  voteTabActive: {
    borderColor: "rgba(96,165,250,0.5)",
    backgroundColor: "rgba(37,99,235,0.18)",
  },
  voteTabOption: { color: "#cbd5e1", fontSize: 12, fontWeight: "600" },
  voteTabOptionActive: { color: "#dbeafe" },
  voteList: { flex: 1 },
  voteListContent: { gap: 8, paddingBottom: 6 },
  voteUserRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.15)",
    backgroundColor: "rgba(15,23,42,0.38)",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  voteUserName: {
    color: "#f1f5f9",
    fontSize: 13,
    fontWeight: "600",
    flex: 1,
    marginRight: 8,
  },
  voteUserTime: { color: "#94a3b8", fontSize: 11 },
  voteEmptyText: {
    color: "#94a3b8",
    textAlign: "center",
    paddingVertical: 18,
    fontSize: 13,
  },
  votePagerRow: {
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  votePagerBtn: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.28)",
    backgroundColor: "rgba(30,41,59,0.45)",
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  votePagerBtnDisabled: { opacity: 0.45 },
  votePagerBtnText: { color: "#cbd5e1", fontSize: 12, fontWeight: "600" },
  votePagerText: { color: "#94a3b8", fontSize: 12, fontWeight: "600" },

  // Stranger
  strangerWaiting: {
    margin: 12,
    padding: 12,
    backgroundColor: "rgba(37,99,235,0.08)",
    borderWidth: 1,
    borderColor: "rgba(37,99,235,0.2)",
    borderRadius: 12,
  },
  strangerWaitingText: { color: "#94a3b8", fontSize: 13, textAlign: "center" },
  strangerRequest: {
    margin: 12,
    backgroundColor: "rgba(30,41,59,0.9)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.2)",
    borderRadius: 14,
    padding: 14,
  },
  strangerRequestHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
  },
  strangerAvatar: { width: 36, height: 36, borderRadius: 18 },
  strangerAvatarPlaceholder: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#2563eb",
    alignItems: "center",
    justifyContent: "center",
  },
  strangerAvatarInitial: { color: "white", fontWeight: "700", fontSize: 14 },
  strangerName: { color: "#f1f5f9", fontWeight: "600", fontSize: 14 },
  strangerSub: { color: "#94a3b8", fontSize: 12 },
  strangerDesc: {
    color: "#94a3b8",
    fontSize: 13,
    marginBottom: 12,
    lineHeight: 18,
  },
  strangerActions: { flexDirection: "row", gap: 8 },
  acceptBtn: {
    flex: 1,
    padding: 8,
    borderRadius: 10,
    backgroundColor: "#2563eb",
    alignItems: "center",
  },
  acceptBtnText: { color: "white", fontWeight: "600", fontSize: 13 },
  declineBtn: {
    flex: 1,
    padding: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(248,113,113,0.4)",
    backgroundColor: "rgba(248,113,113,0.1)",
    alignItems: "center",
  },
  declineBtnText: { color: "#fca5a5", fontWeight: "600", fontSize: 13 },

  // Typing
  typingRow: { height: 20, paddingHorizontal: 16, justifyContent: "center" },
  typingText: { color: "#94a3b8", fontSize: 12 },

  // Input area
  inputWrapper: {
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: Platform.OS === "ios" ? 32 : 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.08)",
    backgroundColor: "#0a1022",
  },
  replyBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(30,64,175,0.22)",
    borderWidth: 1,
    borderColor: "rgba(96,165,250,0.4)",
    borderRadius: 12,
    padding: 8,
    marginBottom: 8,
  },
  replyBannerName: { color: "#bfdbfe", fontSize: 12, fontWeight: "600" },
  replyBannerPreview: { color: "#cbd5e1", fontSize: 12, marginTop: 1 },
  editBanner: {
    backgroundColor: "rgba(234,179,8,.1)",
    borderWidth: 1,
    borderColor: "rgba(234,179,8,.35)",
    borderRadius: 12,
    padding: 8,
    marginBottom: 8,
  },
  editBannerTitle: { color: "#fde047", fontSize: 12, fontWeight: "600" },

  lozaSuggestion: {
    borderWidth: 1,
    borderColor: "rgba(96,165,250,.45)",
    backgroundColor: "rgba(37,99,235,.12)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  lozaSuggestionText: { color: "#bfdbfe", fontSize: 12 },

  actionsRow: {
    flexDirection: "row",
    gap: 4,
    marginBottom: 8,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(148,163,184,0.08)",
  },
  actionIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },

  inputRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  textInput: {
    flex: 1,
    backgroundColor: "#1e293b",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingTop: Platform.OS === "ios" ? 10 : 8,
    paddingBottom: Platform.OS === "ios" ? 10 : 8,
    color: "white",
    fontSize: 15,
    minHeight: 40,
    maxHeight: 100,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.15)",
  },
  sendBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },

  // Modals
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "flex-end",
  },
  popupSheet: {
    backgroundColor: "#0c1a38",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderWidth: 0.5,
    borderColor: "rgba(148,163,184,0.22)",
    padding: 18,
    paddingBottom: Platform.OS === "ios" ? 36 : 20,
  },
  popupTitle: {
    color: "#f1f5f9",
    fontWeight: "700",
    fontSize: 16,
    marginBottom: 14,
  },
  popupAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 13,
    borderRadius: 12,
    borderWidth: 0.5,
    borderColor: "rgba(148,163,184,0.22)",
    backgroundColor: "rgba(255,255,255,0.05)",
    marginBottom: 8,
  },
  popupActionText: { color: "#e2e8f0", fontSize: 14 },
  emptyText: { color: "#94a3b8", fontSize: 12, textAlign: "center" },

  // Audio
  audioHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  recordBadge: {
    backgroundColor: "rgba(100,116,139,0.1)",
    borderWidth: 0.5,
    borderColor: "rgba(100,116,139,0.2)",
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  recordBadgeActive: {
    backgroundColor: "rgba(252,165,165,0.1)",
    borderColor: "rgba(252,165,165,0.25)",
  },
  recordBadgeText: { color: "#64748b", fontSize: 12 },
  recordBadgeTextActive: { color: "#fca5a5" },

  // Sticker
  stickerGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  stickerItem: {
    width: "30%",
    borderRadius: 12,
    borderWidth: 0.5,
    borderColor: "rgba(148,163,184,0.15)",
    backgroundColor: "rgba(255,255,255,0.03)",
    padding: 6,
    alignItems: "center",
  },
  stickerImg: { width: "100%", height: 80 },

  // Poll inputs
  pollInput: {
    borderWidth: 0.5,
    borderColor: "rgba(148,163,184,0.22)",
    backgroundColor: "rgba(255,255,255,0.05)",
    color: "#f1f5f9",
    borderRadius: 11,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    marginBottom: 8,
  },
  pollActions: { flexDirection: "row", gap: 8, marginTop: 6 },
  pollPopupSheet: { maxHeight: "72%" },
  pollScrollContent: { paddingBottom: Platform.OS === "ios" ? 8 : 16 },
  pollAddBtn: {
    borderWidth: 0.5,
    borderColor: "rgba(148,163,184,0.25)",
    borderRadius: 11,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  pollAddBtnText: { color: "#94a3b8", fontSize: 13 },
  pollSubmitBtn: {
    backgroundColor: "#2563eb",
    borderRadius: 11,
    paddingHorizontal: 14,
    paddingVertical: 9,
    flex: 1,
    alignItems: "center",
  },
  pollSubmitBtnText: { color: "white", fontWeight: "600", fontSize: 13 },

  // Reaction menu
  reactionMenuSheet: {
    backgroundColor: "#0c1a38",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 16,
    paddingBottom: Platform.OS === "ios" ? 36 : 20,
  },
  reactionMenuRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  reactionEmojiBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "transparent",
  },
  reactionEmojiBtnActive: {
    borderColor: "rgba(96,165,250,.85)",
    backgroundColor: "rgba(37,99,235,.18)",
  },
  cancelReactionBtn: {
    marginTop: 12,
    alignItems: "center",
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "rgba(248,113,113,.45)",
    borderRadius: 10,
  },
  cancelReactionBtnText: { color: "#fca5a5", fontWeight: "600", fontSize: 13 },

  // Preview
  previewRoot: { flex: 1, backgroundColor: "rgba(2,6,23,0.98)" },
  previewCloseBtn: {
    position: "absolute",
    top: Platform.OS === "ios" ? 56 : 26,
    right: 16,
    zIndex: 2,
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15,23,42,0.72)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.26)",
  },
  previewImageWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    paddingVertical: 18,
  },
  previewErrorText: {
    color: "#cbd5e1",
    fontSize: 14,
    marginBottom: 10,
    textAlign: "center",
  },
  previewImage: { width: "100%", height: "100%" },

  // Context menu
  contextMenu: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#0f172a",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderWidth: 0.5,
    borderColor: "rgba(148,163,184,0.22)",
    padding: 10,
    paddingBottom: Platform.OS === "ios" ? 36 : 16,
  },
  contextMenuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 13,
    borderRadius: 12,
  },
  contextMenuDanger: { marginTop: 4 },
  contextMenuText: { color: "#e2e8f0", fontSize: 14 },
  headerAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  bubbleWrapper: {
    maxWidth: "75%",
  },
  triangleAvatar: {
    width: 44,
    height: 44,
    position: "relative",
  },

  avtTop: {
    width: 22,
    height: 22,
    borderRadius: 11,
    position: "absolute",
    top: 0,
    left: 11,
  },

  avtLeft: {
    width: 22,
    height: 22,
    borderRadius: 11,
    position: "absolute",
    bottom: 0,
    left: 0,
  },

  avtRight: {
    width: 22,
    height: 22,
    borderRadius: 11,
    position: "absolute",
    bottom: 0,
    right: 0,
  },

  moreBadge: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#64748b",
    justifyContent: "center",
    alignItems: "center",
  },
});
